# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('temperature', models.DecimalField(
                    decimal_places=1, max_digits=5)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWeatherByCity',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('month', models.IntegerField()),
                ('boston_temp', models.DecimalField(
                    decimal_places=1, max_digits=5)),
                ('houston_temp', models.DecimalField(
                    decimal_places=1, max_digits=5)),
                ('new_york_temp', models.DecimalField(
                    decimal_places=1, max_digits=5)),
                ('san_francisco_temp', models.DecimalField(
                    decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWeatherSeattle',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('month', models.IntegerField()),
                ('seattle_temp', models.DecimalField(
                    decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('authors', models.ManyToManyField(to='demoproject.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('sale_qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='demoproject.Book')),
                ('bookstore', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='demoproject.BookStore')),
            ],
        ),
        migrations.AddField(
            model_name='bookstore',
            name='city',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='demoproject.City'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='demoproject.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='demoproject.Publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='related',
            field=models.ManyToManyField(
                blank=True,
                related_name='_book_related_+', to='demoproject.Book'),
        ),
    ]
