# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:33
from __future__ import unicode_literals
import pytz
from datetime import datetime, timedelta
from django.db import migrations, models


def initialize_data(apps, _):
    Book = apps.get_model("demoproject", "Book")
    SalesHistory = apps.get_model("demoproject", "SalesHistory")

    for book in Book.objects.all():
        book_id = int(book.pk)
        first_sale = SalesHistory.objects.filter(book=book).first()
        published_at = datetime.combine(
                                    first_sale.sale_date,
                                    datetime.min.time())
        published_at = published_at - timedelta(days=book_id)
        published_at = published_at.replace(
                                        hour=book_id % 24,
                                        minute=(book_id * 2) % 60,
                                        tzinfo=pytz.timezone('Europe/Sofia'),
                                    )
        book.published_at = published_at
        book.save()


class Migration(migrations.Migration):
    """
        Add a new field Book.published_at and initialize with
        random data b/c we use this in the tests.
    """

    dependencies = [
        ('demoproject', '0004_unicode_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(initialize_data),
    ]
